spring:
  thymeleaf:
    cache: false
    mode: HTML


mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql

jdbc:
  isStartSql: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true